project:
  type: website
  output-dir: docs

website:
  title: "AMSA - Fall 2025"
  description: "Course materials for AMSA - Fall 2025"
  site-url: "https://amsa-gei-udl-2526-105013.github.io/course/"
  repo-url: https://github.com/amsa-gei-udl-2526-105013/course/

  sidebar:
    logo: /figs/logo.png
    logo-width: 75px
    logo-height: 75px
    logo-alt: "AMSA Logo"
    pinned: true
    tools:
    - icon: house
      href: "index.html"
      text: "Home"
    - icon: github
      href: "https://github.com/amsa-gei-udl-2526-105013/course/"
      text: "GitHub organization"
    - icon: person-fill
      text: "Sakai"
      href: "https://cv.udl.cat/"

    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - section: Informació del curs
        contents:
          - href: ./course-information/schedule.html
            text: Planificació
      - section: Diapositives
        contents:
          - href: ./slides/01-foundations-of-systems-administration.qmd
            text: Unitat 01 · Fonaments de l'Administració de Sistemes
      - section: Activitats
        contents:
          - section: Unitat 01 · Fonaments de l'Administració de Sistemes
            contents:
              - href: ./exercises/01-foundations-of-systems-administration/01-ex-week1.qmd
                text: Activitat 1 · Configuració d'entorn de virtualització
              - href: ./exercises/01-foundations-of-systems-administration/02-ex-week1.qmd
                text: Activitat 2 · Emulació en mode d'usuari amb QEMU
      - section: Laboratoris
        contents:
          - href: ./laboratories/01-aws-introduction.qmd
            text: Laboratori 01 · Introducció a AWS
          - href: ./laboratories/02-aws-wordpress.qmd
            text: Laboratori 02 · Desplegament d'una aplicació web amb AWS

  
format:
  html:
    toc: true
    theme: 
      - cosmo
      - brand
