<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Gestió centralitzada d’usuaris utiltizant LDAP – AMSA - Fall 2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c30451789a0a2bcd5e941535c675cd30.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Laboratoris</li><li class="breadcrumb-item"><a href="../../laboratories/04-ldap/01-ldap.html">Unitat 04 · Autenticació i Autorització</a></li><li class="breadcrumb-item"><a href="../../laboratories/04-ldap/01-ldap.html">Laboratori 05 · Servei d’Autenticació Centralitzada amb LDAP a AWS</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../figs/logo.png" alt="AMSA Logo" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../../figs/logo.png" alt="AMSA Logo" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="../../index.html" title="Home" class="quarto-navigation-tool px-1" aria-label="Home"><i class="bi bi-house"></i></a>
    <a href="https://github.com/amsa-gei-udl-2526-105013/course/" title="GitHub organization" class="quarto-navigation-tool px-1" aria-label="GitHub organization"><i class="bi bi-github"></i></a>
    <a href="https://cv.udl.cat/" title="Sakai" class="quarto-navigation-tool px-1" aria-label="Sakai"><i class="bi bi-person-fill"></i></a>
</div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Informació del curs</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../.././course-information/schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Planificació</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Diapositives</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides/01-foundations-of-systems-administration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unitat 01 · Fonaments de l’Administració de Sistemes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides/02-booting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unitat 02 · Arrencada del sistema</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides/02-booting-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unitat 02 · Arrencada del sistema (Part 2)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides/02-booting-part3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unitat 02 · Arrencada del sistema (Part 3)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides/03-filesystem-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unitat 03 · Sistemes de fitxers (Part 1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides/03-filesystem-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unitat 03 · Sistemes de fitxers (Part 2)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides/03-filesystem-part3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unitat 03 · Sistemes de fitxers (Part 3)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides/04-authentication-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unitat 04 · Autenticació i Autorització (Part 1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides/04-authentication-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unitat 04 · Autenticació i Autorització (Part 2)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides/05-virtualization-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unitat 05 · Virtualització i Contenidors (Part 1)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Activitats</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Unitat 01 · Fonaments de l’Administració de Sistemes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/01-foundations-of-systems-administration/01-ex-week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 1 · Configuració d’entorn de virtualització</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/01-foundations-of-systems-administration/02-ex-week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 2 · Emulació en mode d’usuari amb QEMU</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Unitat 02 · Arrencada del sistema</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/02-booting/01-ex-week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 1 · Booting amb MBR i BIOS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/02-booting/02-ex-week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 2 · Booting amb UEFI</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/02-booting/03-ex-week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 3 · Dual Boot amb UEFI</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/02-booting/04-ex-week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 4 · Modificant la contrasenya de l’usuari root a través del GRUB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/02-booting/05-ex-week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 5 · Arrencada automàtica d’una partició LUKS amb clau en un disc secundari</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/02-booting/06-ex-week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 6 · Anàlisi del procés d’arrencada amb systemd</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/02-booting/07-ex-week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 7 · Servei de Còpia de Seguretat Automàtica amb systemd</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Unitat 03 · Sistemes de fitxers</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/03-fs/08-ex-week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 8 · Administració bàsica de Sistemes de Fitxers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/03-fs/09-ex-week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 9 · Configuració de RAIDs amb mdadm</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/03-fs/10-ex-week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 10 · Administració de volums lògics amb LVM</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Unitat 04 · Autenticació i Autorització</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/04-accounts/01-lord-of-system.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 11 · Gestió de comptes en un servidor Linux</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/04-accounts/01-pam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 12 · Autenticació de doble factor (2FA) amb PAM</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Unitat 05 · Virtualització i Contenidors</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/05-virtualitzation/01-docker.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activitat 13 · Introducció a Docker</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Laboratoris</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Unitat 01 · Fonaments de l’Administració de Sistemes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../laboratories/01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Laboratori · Fonaments de l’Administració de Sistemes amb AWS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../laboratories/01-foundations/01-aws-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Laboratori 01 · Introducció a AWS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../laboratories/01-foundations/02-aws-wordpress.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Laboratori 02 · Desplegament d’una aplicació web amb AWS</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Networking</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../laboratories/02-network/01-aws-wordpress.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Laboratori 03 · Desplegament d’una aplicació web amb alta disponibilitat amb AWS</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Storage and Services</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../laboratories/03-jupyter/01-aws-jupyter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Laboratori 04 · Servidor de Python al Cloud amb Emmagatzematge S3 Compartit</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true">
 <span class="menu-text">Unitat 04 · Autenticació i Autorització</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../laboratories/04-ldap/01-ldap.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Laboratori 05 · Servei d’Autenticació Centralitzada amb LDAP a AWS</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">Projectes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/01-project/01-project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projecte 1 · Snapshots i Backups amb systemd i initramfs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/02-project/02-project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projecte 2 · Diagnòstic i Resolució d’Incidències</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/03-project/03-project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projecte 3 · Infraestructura LDAP Completa a AWS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../projects/04-project/04-project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projecte 4 · Dockerització i Orquestració d’una API a AWS</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#objectius-del-laboratori" id="toc-objectius-del-laboratori" class="nav-link active" data-scroll-target="#objectius-del-laboratori">🎯 Objectius del laboratori</a></li>
  <li><a href="#infraestructura-a-desplegar" id="toc-infraestructura-a-desplegar" class="nav-link" data-scroll-target="#infraestructura-a-desplegar">🏗️ Infraestructura a desplegar</a></li>
  <li><a href="#què-aprendràs-en-aquest-laboratori" id="toc-què-aprendràs-en-aquest-laboratori" class="nav-link" data-scroll-target="#què-aprendràs-en-aquest-laboratori">🧠 Què aprendràs en aquest laboratori?</a></li>
  <li><a href="#resultats-esperats" id="toc-resultats-esperats" class="nav-link" data-scroll-target="#resultats-esperats">📌 Resultats esperats</a></li>
  <li><a href="#requisits-per-començar-el-laboratori" id="toc-requisits-per-començar-el-laboratori" class="nav-link" data-scroll-target="#requisits-per-començar-el-laboratori">🧩 Requisits per començar el laboratori</a>
  <ul class="collapse">
  <li><a href="#grups-de-seguretat-security-groups" id="toc-grups-de-seguretat-security-groups" class="nav-link" data-scroll-target="#grups-de-seguretat-security-groups">🔐 Grups de seguretat (Security Groups)</a></li>
  </ul></li>
  <li><a href="#part-i-configuració-del-servidor-openldap" id="toc-part-i-configuració-del-servidor-openldap" class="nav-link" data-scroll-target="#part-i-configuració-del-servidor-openldap">PART I – Configuració del servidor OpenLDAP</a>
  <ul class="collapse">
  <li><a href="#installació-deines-i-dependències" id="toc-installació-deines-i-dependències" class="nav-link" data-scroll-target="#installació-deines-i-dependències">🛠️ Instal·lació d’eines i dependències</a></li>
  <li><a href="#descarregar-i-descomprimir-openldap" id="toc-descarregar-i-descomprimir-openldap" class="nav-link" data-scroll-target="#descarregar-i-descomprimir-openldap">📦 Descarregar i descomprimir OpenLDAP</a></li>
  <li><a href="#configuració-i-installació-dopenldap" id="toc-configuració-i-installació-dopenldap" class="nav-link" data-scroll-target="#configuració-i-installació-dopenldap">⚙️ Configuració i instal·lació d’OpenLDAP</a></li>
  <li><a href="#generació-de-contrasenyes-amb-sha-512-ssha-512" id="toc-generació-de-contrasenyes-amb-sha-512-ssha-512" class="nav-link" data-scroll-target="#generació-de-contrasenyes-amb-sha-512-ssha-512">🔐 Generació de contrasenyes amb SHA-512 (SSHA-512)</a></li>
  <li><a href="#configuració-del-servei-slapd.service" id="toc-configuració-del-servei-slapd.service" class="nav-link" data-scroll-target="#configuració-del-servei-slapd.service">⚙️ Configuració del servei <code>slapd.service</code></a></li>
  <li><a href="#configuració-del-servei-ldap" id="toc-configuració-del-servei-ldap" class="nav-link" data-scroll-target="#configuració-del-servei-ldap">⚙️ Configuració del servei LDAP</a></li>
  </ul></li>
  <li><a href="#creació-de-la-base-de-dades-de-configuració-cnconfig" id="toc-creació-de-la-base-de-dades-de-configuració-cnconfig" class="nav-link" data-scroll-target="#creació-de-la-base-de-dades-de-configuració-cnconfig">🧩 Creació de la base de dades de configuració (<code>cn=config</code>)</a>
  <ul class="collapse">
  <li><a href="#conceptes" id="toc-conceptes" class="nav-link" data-scroll-target="#conceptes">Conceptes</a></li>
  <li><a href="#creació-del-fitxer-etcopenldapslapd.ldif" id="toc-creació-del-fitxer-etcopenldapslapd.ldif" class="nav-link" data-scroll-target="#creació-del-fitxer-etcopenldapslapd.ldif">📄 Creació del fitxer /etc/openldap/slapd.ldif</a></li>
  <li><a href="#carregar-la-configuració-inicial-cnconfig-al-servidor-ldap" id="toc-carregar-la-configuració-inicial-cnconfig-al-servidor-ldap" class="nav-link" data-scroll-target="#carregar-la-configuració-inicial-cnconfig-al-servidor-ldap">🏗️ Carregar la configuració inicial (cn=config) al servidor LDAP</a></li>
  <li><a href="#configurant-lestructura-de-la-base-de-dades-del-directori" id="toc-configurant-lestructura-de-la-base-de-dades-del-directori" class="nav-link" data-scroll-target="#configurant-lestructura-de-la-base-de-dades-del-directori">🗂️ Configurant l’estructura de la base de dades del directori</a></li>
  <li><a href="#creació-de-lestructura-del-directori-ldap" id="toc-creació-de-lestructura-del-directori-ldap" class="nav-link" data-scroll-target="#creació-de-lestructura-del-directori-ldap">Creació de l’estructura del directori LDAP</a></li>
  <li><a href="#creació-dusuaris-i-grups-dins-del-directori-ldap" id="toc-creació-dusuaris-i-grups-dins-del-directori-ldap" class="nav-link" data-scroll-target="#creació-dusuaris-i-grups-dins-del-directori-ldap">📂 Creació d’usuaris i grups dins del directori LDAP</a></li>
  <li><a href="#testeig-inicial-de-la-installació-ldap-abans-de-tls" id="toc-testeig-inicial-de-la-installació-ldap-abans-de-tls" class="nav-link" data-scroll-target="#testeig-inicial-de-la-installació-ldap-abans-de-tls">🧪 Testeig inicial de la instal·lació LDAP (abans de TLS)</a></li>
  <li><a href="#altres-comandes-útils-per-a-la-gestió-ldap" id="toc-altres-comandes-útils-per-a-la-gestió-ldap" class="nav-link" data-scroll-target="#altres-comandes-útils-per-a-la-gestió-ldap">Altres comandes útils per a la gestió LDAP</a></li>
  <li><a href="#exercicis-dampliació" id="toc-exercicis-dampliació" class="nav-link" data-scroll-target="#exercicis-dampliació">Exercicis d’ampliació</a></li>
  <li><a href="#configuració-de-certificats-tls-per-ldap-ldaps" id="toc-configuració-de-certificats-tls-per-ldap-ldaps" class="nav-link" data-scroll-target="#configuració-de-certificats-tls-per-ldap-ldaps">🔐 Configuració de certificats TLS per LDAP (LDAPS)</a></li>
  <li><a href="#afegir-la-configuració-tls-al-servidor-ldap" id="toc-afegir-la-configuració-tls-al-servidor-ldap" class="nav-link" data-scroll-target="#afegir-la-configuració-tls-al-servidor-ldap">Afegir la configuració TLS al servidor LDAP</a></li>
  </ul></li>
  <li><a href="#configuració-del-client-ldap" id="toc-configuració-del-client-ldap" class="nav-link" data-scroll-target="#configuració-del-client-ldap">🖥️ Configuració del client LDAP</a>
  <ul class="collapse">
  <li><a href="#installar-els-paquets-necessaris" id="toc-installar-els-paquets-necessaris" class="nav-link" data-scroll-target="#installar-els-paquets-necessaris">Instal·lar els paquets necessaris</a></li>
  <li><a href="#copiar-el-certificat-ca-del-servidor-ldap" id="toc-copiar-el-certificat-ca-del-servidor-ldap" class="nav-link" data-scroll-target="#copiar-el-certificat-ca-del-servidor-ldap">Copiar el certificat CA del servidor LDAP</a></li>
  <li><a href="#configurar-etcopenldapldap.conf" id="toc-configurar-etcopenldapldap.conf" class="nav-link" data-scroll-target="#configurar-etcopenldapldap.conf">Configurar <code>/etc/openldap/ldap.conf</code></a></li>
  <li><a href="#configurar-sssd-etcsssdsssd.conf" id="toc-configurar-sssd-etcsssdsssd.conf" class="nav-link" data-scroll-target="#configurar-sssd-etcsssdsssd.conf">Configurar SSSD <code>/etc/sssd/sssd.conf</code></a></li>
  <li><a href="#configurar-authselect" id="toc-configurar-authselect" class="nav-link" data-scroll-target="#configurar-authselect">Configurar Authselect</a></li>
  <li><a href="#configurar-oddjob-per-a-la-creació-automàtica-de-directoris-dinici" id="toc-configurar-oddjob-per-a-la-creació-automàtica-de-directoris-dinici" class="nav-link" data-scroll-target="#configurar-oddjob-per-a-la-creació-automàtica-de-directoris-dinici">Configurar Oddjob per a la creació automàtica de directoris d’inici</a></li>
  <li><a href="#iniciar-i-habilitar-sssd" id="toc-iniciar-i-habilitar-sssd" class="nav-link" data-scroll-target="#iniciar-i-habilitar-sssd">Iniciar i habilitar SSSD</a></li>
  <li><a href="#testar-la-configuració-del-client-ldap" id="toc-testar-la-configuració-del-client-ldap" class="nav-link" data-scroll-target="#testar-la-configuració-del-client-ldap">Testar la configuració del client LDAP</a></li>
  <li><a href="#testar-amb-creació-manual" id="toc-testar-amb-creació-manual" class="nav-link" data-scroll-target="#testar-amb-creació-manual">Testar amb creació manual</a></li>
  </ul></li>
  <li><a href="#installació-i-configuració-dun-client-web-ldap-lam" id="toc-installació-i-configuració-dun-client-web-ldap-lam" class="nav-link" data-scroll-target="#installació-i-configuració-dun-client-web-ldap-lam">🌐 Instal·lació i configuració d’un client web LDAP (LAM)</a>
  <ul class="collapse">
  <li><a href="#installació-de-dependències" id="toc-installació-de-dependències" class="nav-link" data-scroll-target="#installació-de-dependències">Instal·lació de dependències</a></li>
  <li><a href="#installació-de-lam" id="toc-installació-de-lam" class="nav-link" data-scroll-target="#installació-de-lam">Instal·lació de LAM</a></li>
  <li><a href="#configuració-de-lam" id="toc-configuració-de-lam" class="nav-link" data-scroll-target="#configuració-de-lam">Configuració de LAM</a></li>
  </ul></li>
  <li><a href="#testing-de-lam" id="toc-testing-de-lam" class="nav-link" data-scroll-target="#testing-de-lam">Testing de LAM</a></li>
  <li><a href="#project-03-automatització-amb-aws-i-ansible" id="toc-project-03-automatització-amb-aws-i-ansible" class="nav-link" data-scroll-target="#project-03-automatització-amb-aws-i-ansible">Project 03: Automatització amb AWS i Ansible</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Laboratoris</li><li class="breadcrumb-item"><a href="../../laboratories/04-ldap/01-ldap.html">Unitat 04 · Autenticació i Autorització</a></li><li class="breadcrumb-item"><a href="../../laboratories/04-ldap/01-ldap.html">Laboratori 05 · Servei d’Autenticació Centralitzada amb LDAP a AWS</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Gestió centralitzada d’usuaris utiltizant LDAP</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="objectius-del-laboratori" class="level2">
<h2 class="anchored" data-anchor-id="objectius-del-laboratori">🎯 Objectius del laboratori</h2>
<p>En aquest laboratori desplegarem i configurarem una infraestructura LDAP completa utilitzant tres instàncies EC2 a AWS Academy. L’objectiu és entendre tant el funcionament intern d’un servei d’autenticació centralitzada com la seva integració amb clients Linux i eines d’administració.</p>
</section>
<section id="infraestructura-a-desplegar" class="level2">
<h2 class="anchored" data-anchor-id="infraestructura-a-desplegar">🏗️ Infraestructura a desplegar</h2>
<p>Treballarem amb tres màquines virtuals:</p>
<ul>
<li><strong>Servidor LDAP (OpenLDAP)</strong> : Gestionarà el directori, usuaris, grups i esquemes.</li>
<li><strong>Client LDAP + SSSD</strong>: Permetrà que els usuaris definits al directori es puguin autenticar al sistema Linux.</li>
<li><strong>Servidor web LAM (LDAP Account Manager)</strong>: Oferirà una interfície gràfica per administrar el directori de manera senzilla.</li>
</ul>
</section>
<section id="què-aprendràs-en-aquest-laboratori" class="level2">
<h2 class="anchored" data-anchor-id="què-aprendràs-en-aquest-laboratori">🧠 Què aprendràs en aquest laboratori?</h2>
<p>En finalitzar el laboratori seràs capaç de:</p>
<ul>
<li>Comprendre l’arquitectura i els components bàsics d’un sistema LDAP.</li>
<li>Instal·lar i configurar OpenLDAP en un servidor Linux.</li>
<li>Activar TLS/SSL i utilitzar LDAPS (port 636) per a connexions segures.</li>
<li>Crear i gestionar usuaris, grups i unitats organitzatives (OU) al directori.</li>
<li>Configurar un client Linux perquè utilitzi LDAP per autenticar usuaris (PAM + SSSD).</li>
<li>Utilitzar LDAP Account Manager (LAM) per administrar visualment el directori.</li>
<li>Verificar que un usuari creat al directori pot iniciar sessió al client Linux.</li>
</ul>
</section>
<section id="resultats-esperats" class="level2">
<h2 class="anchored" data-anchor-id="resultats-esperats">📌 Resultats esperats</h2>
<p>En acabar hauràs desplegat un entorn funcional que simula un sistema d’autenticació corporatiu, tal com es trobaria en una infraestructura real d’empresa.</p>
<hr>
</section>
<section id="requisits-per-començar-el-laboratori" class="level2">
<h2 class="anchored" data-anchor-id="requisits-per-començar-el-laboratori">🧩 Requisits per començar el laboratori</h2>
<p>Per completar aquest laboratori necessitareu tres instàncies EC2 que formaran la infraestructura LDAP. Utilitzarem Amazon Linux 2023, ja que és estable, lleuger i compatible amb les eines necessàries.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 12%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Rol</th>
<th>Nom recomanat</th>
<th>Ports oberts</th>
<th>Programari necessari</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Servidor LDAP</strong></td>
<td><code>OpenLDAP-AMSA-Server</code></td>
<td>22, 389, 636</td>
<td>OpenLDAP instal·lat i configurat amb TLS/SSL</td>
</tr>
<tr class="even">
<td><strong>Client LDAP</strong></td>
<td><code>LDAP-Client</code></td>
<td>22</td>
<td>SSSD, Paquets <code>openldap-clients</code></td>
</tr>
<tr class="odd">
<td><strong>Servidor LAM</strong></td>
<td><code>LAM-WebServer</code></td>
<td>22, 80</td>
<td>Apache HTTPD + PHP + LDAP Account Manager (LAM)</td>
</tr>
</tbody>
</table>
<section id="grups-de-seguretat-security-groups" class="level3">
<h3 class="anchored" data-anchor-id="grups-de-seguretat-security-groups">🔐 Grups de seguretat (Security Groups)</h3>
<ul>
<li><strong>Regles d’entrada</strong>:</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rol</th>
<th>Ports necessaris oberts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Servidor LDAP</strong></td>
<td>SSH (22/tcp), LDAP (389/tcp), LDAPS (636/tcp)</td>
</tr>
<tr class="even">
<td><strong>Client LDAP</strong></td>
<td>SSH (22/tcp)</td>
</tr>
<tr class="odd">
<td><strong>Servidor LAM</strong></td>
<td>SSH (22/tcp), HTTP (80/tcp)</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Regles de sortida</strong>: Totes per defecte (Allow All).</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Checkpoint (✔)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Verifica que:</p>
<ul>
<li>Les 3 instàncies EC2 estan creades. Apunta el DNS públic de cadascuna.</li>
<li>Assegura’t que pots connectar-te via SSH a cada instància.</li>
<li>Cada servei té els ports necessaris oberts al seu Security Group. Per comprovar-ho pots fer servir la comanda <code>nc -zv &lt;IP_SERVIDOR&gt; &lt;PORT&gt;</code>.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="part-i-configuració-del-servidor-openldap" class="level2">
<h2 class="anchored" data-anchor-id="part-i-configuració-del-servidor-openldap">PART I – Configuració del servidor OpenLDAP</h2>
<section id="installació-deines-i-dependències" class="level3">
<h3 class="anchored" data-anchor-id="installació-deines-i-dependències">🛠️ Instal·lació d’eines i dependències</h3>
<p>Segons el manual oficial d’instal·lació <a href="https://www.openldap.org/doc/admin26/install.html">manual d’instal·lació</a>, OpenLDAP requereix un conjunt de biblioteques i eines per poder compilar:</p>
<ul>
<li>Compilador C (gcc)</li>
<li>OpenSSL → necessari per TLS/SSL</li>
<li>Cyrus SASL → suport d’autenticació avançada</li>
<li>libevent → millora del rendiment en gestió d’esdeveniments</li>
<li>libargon2 / libsodium → hashing de contrasenyes</li>
<li>Eines de compilació: make, autoconf, libtool</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> dnf install <span class="dt">\</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>cyrus-sasl-devel make libtool autoconf libtool-ltdl-devel <span class="dt">\</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>openssl-devel libdb-devel tar gcc perl perl-devel wget vim <span class="at">-y</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="descarregar-i-descomprimir-openldap" class="level3">
<h3 class="anchored" data-anchor-id="descarregar-i-descomprimir-openldap">📦 Descarregar i descomprimir OpenLDAP</h3>
<p>Descarregarem el paquet des de la pàgina oficial mitjançant FTP i el descomprimirem:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="va">VER</span><span class="op">=</span><span class="st">"2.6.3"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> /tmp</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">wget</span> ftp://ftp.openldap.org/pub/OpenLDAP/openldap-release/openldap-<span class="va">$VER</span>.tgz</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tar</span> xzf openldap-<span class="va">$VER</span>.tgz</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> openldap-<span class="va">$VER</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled" title="`/tmp?`">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><code>/tmp?</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>/tmp</code>: És un directori temporal, ideal per compilar programari sense embrutar el sistema. Un cop reiniciem, tot el que hi ha a <code>/tmp</code> es perd.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Checkpoint (✔)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><code>pwd</code> ha de mostrar <code>/tmp/openldap-2.6.3</code>.</li>
<li><code>ls -lah /tmp/openldap-2.6.3</code> ha de llistar els fitxers font d’OpenLDAP.</li>
</ul>
</div>
</div>
</section>
<section id="configuració-i-installació-dopenldap" class="level3">
<h3 class="anchored" data-anchor-id="configuració-i-installació-dopenldap">⚙️ Configuració i instal·lació d’OpenLDAP</h3>
<p>Un cop descarregat el codi font, procedirem a configurar, compilar i instal·lar OpenLDAP. Aquest procés ens permet controlar exactament quines funcionalitats tindrà el servidor.</p>
<ol type="1">
<li><p>Configurem el paquet amb les opcions que necessitem:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">./configure</span> <span class="at">--prefix</span><span class="op">=</span>/usr <span class="at">--sysconfdir</span><span class="op">=</span>/etc <span class="at">--disable-static</span> <span class="dt">\</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>--enable-debug <span class="at">--with-tls</span><span class="op">=</span>openssl <span class="at">--with-cyrus-sasl</span> <span class="at">--enable-dynamic</span> <span class="dt">\</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>--enable-crypt <span class="at">--enable-spasswd</span> <span class="at">--enable-slapd</span> <span class="at">--enable-modules</span> <span class="dt">\</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>--enable-rlookups  <span class="at">--disable-sql</span>  <span class="dt">\</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>--enable-ppolicy <span class="at">--enable-syslog</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><code>--prefix=/usr</code> → OpenLDAP s’instal·larà sota /usr (no /usr/local).</li>
<li><code>--sysconfdir=/etc</code> → Fitxers de configuració a /etc/openldap.</li>
<li><code>--with-tls=openssl</code> → Activa TLS/SSL (LDAPS).</li>
<li><code>--enable-slapd</code> → Construeix el servidor LDAP.</li>
<li><code>--enable-modules</code> → Permet càrrega dinàmica de mòduls.</li>
<li><code>--enable-ppolicy</code> → Suport de polítiques de contrasenyes.</li>
<li><code>--enable-debug</code> → Útil en entorns docents.</li>
</ul></li>
<li><p>Compilem i instal·lem el paquet:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> make depend</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> make</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
</ol>
<div class="callout callout-style-default callout-warning callout-titled" title="Dev/Prod">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Dev/Prod
</div>
</div>
<div class="callout-body-container callout-body">
<p>El comandament <code>make test</code> executa proves d’integritat, però pot trigar força estona i no és necessari en aquest laboratori. En producció, sí que es recomana.</p>
</div>
</div>
<ol type="1">
<li><p>Compilem els mòduls addicionals per suportar SHA-2: Per defecte, OpenLDAP utilitza SHA-1, que avui dia és insuficientment segur. Activarem suport per a SHA-256, SHA-384 i SHA-512.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> contrib/slapd-modules/passwd/sha2</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> make</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p>Instal·lem el servidor OpenLDAP:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> ../../../.. <span class="co"># Tornem a la carpeta inicial</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> make install</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
</ol>
<p>Aquesta comanda instal·larà: - el servidor <strong>slapd</strong> - eines d’administració (<code>ldapadd</code>, <code>ldapsearch</code>, etc.) - configuració base a <code>/etc/openldap/</code></p>
<ol start="5" type="1">
<li><p>Instal·lem els mòduls addicionals relacionats amb SHA-2:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> contrib/slapd-modules/passwd/sha2</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> make install</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
</ol>
<p>En aquest punt, si tot ha anat bé, ja tindrem el servidor LDAP instal·lat al nostre servidor. Podeu comprovar:</p>
<ul>
<li><p>Els fitxers de configuració a <code>/etc/openldap/</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> ls <span class="at">-la</span> /etc/openldap/</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p>Els mòduls instal·lats a <code>/usr/local/libexec/openldap/</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> ls <span class="at">-la</span> /usr/local/libexec/openldap/</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (o /usr/libexec/openldap/ si la vostra configuració així ho ha definit).</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Checkpoint (✔)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Assegura’t que la instal·lació ha anat bé:</p>
<ul>
<li>Verifica que existeix el directori <code>/etc/openldap</code>.</li>
<li>Verifica que existeix el directori <code>/usr/local/libexec/openldap</code>.</li>
<li>Verifica que existeix <code>/usr/local/libexec/openldap/pw-sha2.la</code>.</li>
<li>Verifica <code>slapd -VV</code> per veure la versió i els mòduls carregats.</li>
</ul>
<p>Si tot és correcte, ja tens OpenLDAP instal·lat i llest per configurar.</p>
</div>
</div>
</section>
<section id="generació-de-contrasenyes-amb-sha-512-ssha-512" class="level3">
<h3 class="anchored" data-anchor-id="generació-de-contrasenyes-amb-sha-512-ssha-512">🔐 Generació de contrasenyes amb SHA-512 (SSHA-512)</h3>
<p>Un cop instal·lats els mòduls SHA-2, podem generar contrasenyes utilitzant l’algorisme SSHA-512, que és molt més segur que el tradicional SHA-1. Aquest tipus de hash és el que s’utilitzarà per emmagatzemar contrasenyes dins del directori LDAP.</p>
<section id="generació-del-hash-amb-slappasswd" class="level4">
<h4 class="anchored" data-anchor-id="generació-del-hash-amb-slappasswd">🛠️ Generació del hash amb <code>slappasswd</code></h4>
<p>Utiltizarem la comanda <code>slappasswd</code> on cal indicar:</p>
<ul>
<li>quin algorisme de hash volem utilitzar (<code>-h "{SSHA512}"</code>), en aquest cas SHA-512.</li>
<li>els mòduls que implementen aquest algorisme (<code>-o module-load=pw-sha2.la</code>).</li>
<li>la ruta on es troben aquests mòduls (<code>-o module-path=/usr/local/libexec/openldap</code>).</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="ex">slappasswd</span> <span class="at">-h</span> <span class="st">"{SSHA512}"</span> <span class="at">-o</span> module-load=pw-sha2.la <span class="at">-o</span> module-path=/usr/local/libexec/openldap</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="introducció-de-la-contrasenya" class="level4">
<h4 class="anchored" data-anchor-id="introducció-de-la-contrasenya">🔑 Introducció de la contrasenya</h4>
<p>Quan executeu la comanda, se us demanarà la contrasenya:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="ex">New</span> password: <span class="pp">********</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Re-enter</span> new password: <span class="pp">********</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-caution callout-titled" title="Seguretat de la contrasenya">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Seguretat de la contrasenya
</div>
</div>
<div class="callout-body-container callout-body">
<p>En l’exemple del laboratori utilitzem 1234 per simplicitat, però en entorns reals això seria extremadament insegur.</p>
</div>
</div>
</section>
<section id="exemple-de-resultat" class="level4">
<h4 class="anchored" data-anchor-id="exemple-de-resultat">🧮 Exemple de resultat</h4>
<p>El resultat generat serà un hash llarg similar al següent:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="ex">{SSHA512}CBVaUdQC9mVvAi+0O92J3hA+aPdiWUqf4lVr6bGRAUsFJX5aFOEb+1pSsY8PQwW1UKuuCGO2+160HotnfjXIaRKlryVekLnu</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Aquesta cadena és el valor que es pot inserir al directori LDAP en atributs com <strong>userPassword</strong>.</p>
</section>
</section>
<section id="configuració-del-servei-slapd.service" class="level3">
<h3 class="anchored" data-anchor-id="configuració-del-servei-slapd.service">⚙️ Configuració del servei <code>slapd.service</code></h3>
<p>És una bona pràctica de seguretat que qualsevol servei del sistema s’executi amb un usuari propi i amb permisos mínims. Això evita que un possible atac comprometi tot el sistema. El servidor LDAP (<code>slapd</code>) no ha de ser executat com a <strong>root</strong>. En lloc d’això, crearem un usuari dedicat i un grup dedicat amb permisos estrictament limitats.</p>
<p>Crearem un grup de sistema anomenat ldap amb un GID fixat:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> groupadd <span class="at">-g</span> 55 ldap</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled" title="Per què gid 55?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Per què gid 55?
</div>
</div>
<div class="callout-body-container callout-body">
<p>El GID 55 és una convenció comuna per al grup ldap en moltes distribucions Linux. Utilitzar un GID fixat ajuda a mantenir la coherència entre diferents sistemes i facilita la gestió d’usuaris i permisos relacionats amb el servei LDAP. Facilita també la migració o sincronització de dades entre sistemes.</p>
</div>
</div>
<p>Crearem un usuari per al servei LDAP:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> useradd <span class="at">-r</span> <span class="at">-M</span> <span class="at">-d</span> /var/lib/openldap <span class="at">-u</span> 55 <span class="at">-g</span> 55 <span class="at">-s</span> /usr/sbin/nologin ldap</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><code>-r</code> → crea un usuari de sistema (sense entrada en <code>/etc/login.defs</code>).</li>
<li><code>-M</code> → no crea directori home (evita carpetes innecessàries).</li>
<li><code>-d /var/lib/openldap</code> → defineix el directori “base” del servei.</li>
<li><code>-u 55</code> → UID específic, alineat amb el GID creat.</li>
<li><code>-g 55</code> → assigna el grup ldap.</li>
<li><code>-s /usr/sbin/nologin</code> → impedeix que l’usuari iniciï sessió interactiva.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="**Least Privilege Principle**">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><strong>Least Privilege Principle</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p>El servei LDAP tindrà només els permisos que necessiti, i res més.</p>
</div>
</div>
</section>
<section id="configuració-del-servei-ldap" class="level3">
<h3 class="anchored" data-anchor-id="configuració-del-servei-ldap">⚙️ Configuració del servei LDAP</h3>
<section id="creació-dels-directoris-necessaris" class="level4">
<h4 class="anchored" data-anchor-id="creació-dels-directoris-necessaris">📁 Creació dels directoris necessaris</h4>
<p>OpenLDAP utilitza dos elements importants:</p>
<ul>
<li><strong>Directori de dades</strong> → conté la base de dades i el PID del servei</li>
<li><strong>Directori de configuració slapd.d</strong> → conté la configuració dinàmica generada per slapadd i slapd</li>
</ul>
<p>Creem-los:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> mkdir <span class="at">-p</span> /var/lib/openldap</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> mkdir <span class="at">-p</span> /etc/openldap/slapd.d</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="assignació-de-permisos" class="level4">
<h4 class="anchored" data-anchor-id="assignació-de-permisos">🛡️ Assignació de permisos</h4>
<section id="assignació-de-permisos-al-directori-de-dades" class="level5">
<h5 class="anchored" data-anchor-id="assignació-de-permisos-al-directori-de-dades">Assignació de permisos al directori de dades</h5>
<p>Com hem creat abans l’usuari i grup ldap, ara assignarem permisos correctes.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> chown <span class="at">-R</span> ldap:ldap /var/lib/openldap</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Això permet que el servei pugui crear els fitxers de BD, sockets i el PID.</p>
</section>
<section id="permisos-al-fitxer-de-configuració" class="level5">
<h5 class="anchored" data-anchor-id="permisos-al-fitxer-de-configuració">Permisos al fitxer de configuració</h5>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> chown root:ldap /etc/openldap/slapd.conf</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> chmod 640 /etc/openldap/slapd.conf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>El fitxer de configuració ha de ser propietat de root, però el grup ldap ha de tenir permisos de lectura. Això permet que el servei pugui llegir la configuració, però evita que altres usuaris no autoritzats hi accedeixin. Els permisos 640 signifiquen: el propietari (root) té permisos de lectura i escriptura, el grup (ldap) té permisos de lectura, i altres usuaris no tenen cap permís.</p>
</section>
</section>
<section id="creació-del-fitxer-de-servei-systemd" class="level4">
<h4 class="anchored" data-anchor-id="creació-del-fitxer-de-servei-systemd">🛠️ Creació del fitxer de servei Systemd</h4>
<p>Ara crearem un servei slapd.service perquè OpenLDAP s’integri amb systemd i pugui arrencar automàticament amb el sistema.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> bash <span class="at">-c</span> <span class="st">"cat &gt; /etc/systemd/system/slapd.service &lt;&lt; 'EOL'</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="st">[Unit]</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="st">Description=OpenLDAP Server Daemon</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="st">After=syslog.target network-online.target</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="st">Documentation=man:slapd</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="st">Documentation=man:slapd-mdb</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="st">[Service]</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="st">Type=forking</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="st">PIDFile=/var/lib/openldap/slapd.pid</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="st">Environment=</span><span class="dt">\"</span><span class="st">SLAPD_URLS=ldap:/// ldapi:/// ldaps:///</span><span class="dt">\"</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="st">Environment=</span><span class="dt">\"</span><span class="st">SLAPD_OPTIONS=-F /etc/openldap/slapd.d</span><span class="dt">\"</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="st">ExecStart=/usr/libexec/slapd -u ldap -g ldap -h </span><span class="dt">\$</span><span class="st">{SLAPD_URLS} </span><span class="dt">\$</span><span class="st">SLAPD_OPTIONS</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="st">[Install]</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="st">WantedBy=multi-user.target</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="st">EOL"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>En la secció <strong>[Unit]</strong> definim el nom i les dependències del servei. El directiu <code>After=syslog.target network-online.target</code> garanteix que <code>slapd</code> no s’iniciï fins que el sistema de registre (<code>syslog</code>) i la connexió de xarxa estiguin plenament operatius.</p>
<p>En la secció <strong>[Service]</strong> especifiquem que el servei és de tipus <em>forking</em>, ja que el dimoni slapd es bifurca i continua executant-se en segon pla. També indiquem el fitxer PID que <em>systemd</em> utilitzarà per controlar el procés, les variables d’entorn i la comanda d’inici. La variable <code>SLAPD_URLS</code> defineix les URL on el servidor escoltarà connexions:</p>
<ul>
<li>ldap:/// → LDAP per TCP (port 389)</li>
<li>ldapi:/// → socket Unix local</li>
<li>ldaps:/// → LDAP sobre TLS (port 636)</li>
</ul>
<p>La variable <code>SLAPD_OPTIONS</code> especifica la ubicació del directori de configuració dinàmica (<code>slapd.d</code>), que és el mètode modern de configuració d’OpenLDAP.</p>
<p>Finalment, en la secció <strong>[Install]</strong> indiquem que el servei ha d’activar-se automàticament en l’objectiu <code>multi-user.target</code>, que correspon al nivell d’execució típic en servidors Linux.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Abans d'iniciar el servei">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Abans d’iniciar el servei
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una bona pràctica és reinciar <strong>systemd</strong> per informar-lo dels nous serveis creats: <code>sudo systemctl daemon-reload</code>.</p>
</div>
</div>
</section>
</section>
</section>
<section id="creació-de-la-base-de-dades-de-configuració-cnconfig" class="level2">
<h2 class="anchored" data-anchor-id="creació-de-la-base-de-dades-de-configuració-cnconfig">🧩 Creació de la base de dades de configuració (<code>cn=config</code>)</h2>
<p>Abans que <code>slapd</code> pugui funcionar, cal inicialitzar la base de dades de configuració dinàmica d’OpenLDAP. Aquesta configuració és diferent de la base de dades de dades (on viuran els usuaris) i s’anomena <code>cn=config</code>.</p>
<p><code>cn=config</code> funciona com una BD LDAP normal: - tot són objectes… - cada objecte té un DN… - i cada DN té objectClasses i atributs.</p>
<p>Aquesta estructura substitueix l’antic slapd.conf, i és molt més flexible.</p>
<section id="conceptes" class="level3">
<h3 class="anchored" data-anchor-id="conceptes">Conceptes</h3>
<section id="configuració-global-dn-cnconfig" class="level4">
<h4 class="anchored" data-anchor-id="configuració-global-dn-cnconfig">Configuració global (<code>dn: cn=config</code>)</h4>
<p>El <strong>dn</strong> indica el nom distintiu de l’objecte dins de l’arbre LDAP. En aquest cas, <code>cn=config</code> és el nom distintiu per a la configuració global del servidor LDAP. Defineix paràmetres generals que afecten tot el servidor:</p>
<ul>
<li>Rutes per als fitxers de PID i arguments (.pid, .args)</li>
<li>Configuració TLS mínima</li>
<li>Política general del dimoni</li>
</ul>
</section>
<section id="mòduls-dn-cnmodulecnconfig" class="level4">
<h4 class="anchored" data-anchor-id="mòduls-dn-cnmodulecnconfig">Mòduls (<code>dn: cn=module,cn=config</code>)</h4>
<p>Els mòduls són components addicionals que amplien la funcionalitat del servidor LDAP. En aquest cas, carreguem:</p>
<ul>
<li>back_mdb.la → el backend de base de dades MDB (el més modern i recomanat)</li>
<li>pw-sha2.la → suport de contrasenyes SHA-256/384/512</li>
<li>⚠️ Nota: El mòdul pw-sha2.la pot estar a /usr/libexec/openldap o /usr/local/libexec/openldap segons la compilació. Per això el fitxer defineix dues entrades.</li>
</ul>
</section>
<section id="esquemes-cnschemacnconfig" class="level4">
<h4 class="anchored" data-anchor-id="esquemes-cnschemacnconfig">Esquemes — <code>cn=schema,cn=config</code></h4>
<p>Els esquemes defineixen quins objectes i atributs existeixen en el directori. En aquest cas, carreguem els esquemes típics:</p>
<ul>
<li><strong>core</strong>: objectes bàsics (person, organization, organizationalUnit, etc.)</li>
<li><strong>cosine</strong>: amplia atributs i objectes estàndard</li>
<li><strong>nis</strong>: atributs relacionats amb usuaris i grups d’estil Unix/NIS</li>
<li><strong>inetorgperson</strong>: l’esquema més utilitzat per comptes d’usuari moderns (mail, telephoneNumber, etc.)</li>
</ul>
</section>
<section id="frontend-dn-olcdatabasefrontendcnconfig" class="level4">
<h4 class="anchored" data-anchor-id="frontend-dn-olcdatabasefrontendcnconfig">Frontend — <code>dn: olcDatabase=frontend,cn=config</code></h4>
<p>Controla com s’accedeixen totes les BDs. Nosaltres definirem:</p>
<ul>
<li>Quin hash utilitzar per defecte → {SSHA512}</li>
<li>Permisos:
<ul>
<li>tothom pot llegir cn=Subschema</li>
<li>root local UNIX (peercred) pot administrar TOT</li>
</ul></li>
</ul>
</section>
<section id="base-de-dades-de-configuració-dn-olcdatabaseconfigcnconfig" class="level4">
<h4 class="anchored" data-anchor-id="base-de-dades-de-configuració-dn-olcdatabaseconfigcnconfig">Base de dades de configuració — <code>dn: olcDatabase=config,cn=config</code></h4>
<p>Defineix permisos acl per accedir al propi <code>cn=config</code>.</p>
</section>
</section>
<section id="creació-del-fitxer-etcopenldapslapd.ldif" class="level3">
<h3 class="anchored" data-anchor-id="creació-del-fitxer-etcopenldapslapd.ldif">📄 Creació del fitxer /etc/openldap/slapd.ldif</h3>
<p>Aquest LDIF conté tota la configuració inicial de slapd. El crearem així:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> bash <span class="at">-c</span> <span class="st">"cat &gt; /etc/openldap/slapd.ldif &lt;&lt; 'EOL'</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="st">dn: cn=config</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: olcGlobal</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="st">cn: config</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="st">olcArgsFile: /var/lib/openldap/slapd.args</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="st">olcPidFile: /var/lib/openldap/slapd.pid</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="st">olcTLSCipherSuite: TLSv1.2:HIGH:\!aNULL:\!eNULL</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="st">olcTLSProtocolMin: 3.3</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="st">dn: cn=schema,cn=config</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: olcSchemaConfig</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="st">cn: schema</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="st">dn: cn=module,cn=config</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: olcModuleList</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="st">cn: module</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="st">olcModulepath: /usr/libexec/openldap</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="st">olcModuleload: back_mdb.la</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="st">dn: cn=module,cn=config</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: olcModuleList</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="st">cn: module</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="st">olcModulepath: /usr/local/libexec/openldap</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a><span class="st">olcModuleload: pw-sha2.la</span></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a><span class="st">include: file:///etc/openldap/schema/core.ldif</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a><span class="st">include: file:///etc/openldap/schema/cosine.ldif</span></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a><span class="st">include: file:///etc/openldap/schema/nis.ldif</span></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="st">include: file:///etc/openldap/schema/inetorgperson.ldif</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a><span class="st">dn: olcDatabase=frontend,cn=config</span></span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: olcDatabaseConfig</span></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: olcFrontendConfig</span></span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a><span class="st">olcDatabase: frontend</span></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="st">olcPasswordHash: {SSHA512}CBVaUdQC9mVvAi+0O92J3hA+aPdiWUqf4lVr6bGRAUsFJX5aFOEb+1pSsY8PQwW1UKuuCGO2+160HotnfjXIaRKlryVekLnu</span></span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a><span class="st">olcAccess: to dn.base=</span><span class="dt">\"</span><span class="st">cn=Subschema</span><span class="dt">\"</span><span class="st"> by * read</span></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a><span class="st">olcAccess: to *</span></span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a><span class="st">  by dn.base=</span><span class="dt">\"</span><span class="st">gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth</span><span class="dt">\"</span><span class="st"> manage</span></span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a><span class="st">  by * none</span></span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a><span class="st">dn: olcDatabase=config,cn=config</span></span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: olcDatabaseConfig</span></span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a><span class="st">olcDatabase: config</span></span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a><span class="st">olcRootDN: cn=config</span></span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a><span class="st">olcAccess: to *</span></span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a><span class="st">  by dn.base=</span><span class="dt">\"</span><span class="st">gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth</span><span class="dt">\"</span><span class="st"> manage</span></span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a><span class="st">  by * none</span></span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a><span class="st">EOL"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>El script anterior té un problema: <code>olcTLSCipherSuite: TLSv1.2:HIGH:\!aNULL:\!eNULL</code> conté caràcters especials (<code>\!</code>) per eliminar-los feu:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> sed <span class="at">-i</span> <span class="st">'s/olcTLSCipherSuite: TLSv1\.2:HIGH:\\!aNULL:\\!eNULL/olcTLSCipherSuite: TLSv1.2:HIGH:!aNULL:!eNULL/'</span> /etc/openldap/slapd.ldif</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="carregar-la-configuració-inicial-cnconfig-al-servidor-ldap" class="level3">
<h3 class="anchored" data-anchor-id="carregar-la-configuració-inicial-cnconfig-al-servidor-ldap">🏗️ Carregar la configuració inicial (cn=config) al servidor LDAP</h3>
<p>En aquest punt, ja hem creat el fitxer <code>slapd.ldif</code> que descriu tota la configuració del servidor LDAP:</p>
<ul>
<li>paràmetres globals</li>
<li>mòduls i esquemes</li>
<li>ACL i bases de dades internes</li>
</ul>
<p>Ara cal carregar aquesta configuració dins la base de dades <code>cn=config</code> utilitzant l’eina <code>slapadd</code>.</p>
<section id="pas-1-carregar-la-configuració-amb-slapadd" class="level4">
<h4 class="anchored" data-anchor-id="pas-1-carregar-la-configuració-amb-slapadd">Pas 1 — Carregar la configuració amb <code>slapadd</code></h4>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> /etc/openldap/</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> slapadd <span class="at">-n</span> 0 <span class="at">-F</span> /etc/openldap/slapd.d <span class="at">-l</span> /etc/openldap/slapd.ldif</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> chown <span class="at">-R</span> ldap:ldap /etc/openldap/slapd.d</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><code>slapadd</code> → importa dades directament a una base de dades LDAP sense passar pel servidor.</li>
<li><code>-n 0</code> → indica que volem modificar la base número 0, que sempre correspon a <code>cn=config</code>.</li>
<li><code>-F /etc/openldap/slapd.d</code> → defineix el directori on s’escriuran els fitxers de configuració dinàmica.</li>
<li><code>-l slapd.ldif</code> → fitxer amb el contingut que volem carregar.</li>
</ul>
<p>Després de carregar la configuració, canviem els permisos perquè el servei LDAP (<strong>slapd</strong>) pugui llegir i escriure al directori <code>slapd.d</code>.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Solució d'errors">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Solució d’errors
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si es produeix un error, podeu eliminar la base de dades i tornar a carregar la configuració. Per fer-ho, <code>sudo rm -rf /etc/openldap/slapd.d/*</code> i torneu a executar la comanda <code>slapadd</code>.</p>
</div>
</div>
</section>
<section id="pas-2-iniciar-el-servei-ldap" class="level4">
<h4 class="anchored" data-anchor-id="pas-2-iniciar-el-servei-ldap">Pas 2 — Iniciar el servei LDAP</h4>
<p>Un cop la base de dades <code>cn=config</code> està creada, ja podem arrencar <code>slapd</code> com a servei <strong>systemd</strong>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> systemctl enable <span class="at">--now</span> slapd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Checkpoint (✔)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Verifica que el servei s’ha iniciat correctament:</p>
<ul>
<li>Comprova l’estat del servei amb: <code>systemctl status slapd</code></li>
</ul>
</div>
</div>
</section>
</section>
<section id="configurant-lestructura-de-la-base-de-dades-del-directori" class="level3">
<h3 class="anchored" data-anchor-id="configurant-lestructura-de-la-base-de-dades-del-directori">🗂️ Configurant l’estructura de la base de dades del directori</h3>
<p>Un cop tenim configurada la base <code>cn=config</code>, és moment de crear la base de dades LDAP que contindrà les dades reals: <em>usuaris, grups i unitats organitzatives</em>. Aquesta base de dades es defineix mitjançant una entrada dins <code>cn=config</code> anomenada: <code>dn: olcDatabase=mdb,cn=config</code>.</p>
<section id="rootdn.ldif-creació-de-lusuari-admin-i-configuració-de-la-base-de-dades" class="level4">
<h4 class="anchored" data-anchor-id="rootdn.ldif-creació-de-lusuari-admin-i-configuració-de-la-base-de-dades"><code>rootdn.ldif</code> — Creació de l’usuari admin i configuració de la base de dades</h4>
<p>Crearem un fitxer amb la configuració de la base de dades principal i el root admin.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="va">BASE</span><span class="op">=</span><span class="st">"dc=amsa,dc=udl,dc=cat"</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> bash <span class="at">-c</span> <span class="st">"cat &lt;&lt; EOL &gt; /etc/openldap/rootdn.ldif</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="st">dn: olcDatabase=mdb,cn=config</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: olcDatabaseConfig</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: olcMdbConfig</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="st">olcDatabase: mdb</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="st">olcDbMaxSize: 42949672960</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="st">olcDbDirectory: /var/lib/openldap</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="st">olcSuffix: </span><span class="va">$BASE</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="st">olcRootDN: cn=admin,</span><span class="va">$BASE</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="st">olcRootPW: {SSHA512}CBVaUdQC9mVvAi+0O92J3hA+aPdiWUqf4lVr6bGRAUsFJX5aFOEb+1pSsY8PQwW1UKuuCGO2+160HotnfjXIaRKlryVekLnu</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="st">olcDbIndex: uid pres,eq</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="st">olcDbIndex: cn,sn pres,eq,approx,sub</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="st">olcDbIndex: mail pres,eq,sub</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="st">olcDbIndex: objectClass pres,eq</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="st">olcDbIndex: loginShell pres,eq</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="st">olcAccess: to attrs=userPassword,shadowLastChange,shadowExpire</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a><span class="st">  by self write</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="st">  by anonymous auth</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="st">  by dn.subtree=</span><span class="dt">\"</span><span class="st">gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth</span><span class="dt">\"</span><span class="st"> manage</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a><span class="st">  by dn.subtree=</span><span class="dt">\"</span><span class="st">ou=system,</span><span class="va">$BASE</span><span class="dt">\"</span><span class="st"> read</span></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="st">  by * none</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a><span class="st">olcAccess: to dn.subtree=</span><span class="dt">\"</span><span class="st">ou=system </span><span class="va">$BASE</span><span class="dt">\"</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a><span class="st">  by dn.subtree=</span><span class="dt">\"</span><span class="st">gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth</span><span class="dt">\"</span><span class="st"> manage</span></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a><span class="st">  by * none</span></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a><span class="st">olcAccess: to dn.subtree=</span><span class="dt">\"</span><span class="va">$BASE</span><span class="dt">\"</span></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a><span class="st">  by dn.subtree=</span><span class="dt">\"</span><span class="st">gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth</span><span class="dt">\"</span><span class="st"> manage</span></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a><span class="st">  by users read</span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a><span class="st">  by * none</span></span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a><span class="st">EOL"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Observa que:</p>
<ul>
<li>El node arrel de la base de dades serà <code>dc=amsa,dc=udl,dc=cat</code>. Aquest node defineix l’abast del directori LDAP i és on s’emmagatzemaran tots els usuaris i grups. Tot el que crearem viurà sota aquest node.</li>
<li>L’usuari administrador serà <code>cn=admin,dc=amsa,dc=udl,dc=cat</code>. Aquest usuari tindrà privilegis elevats per gestionar el directori. La seva contrasenya està definida mitjançant un hash SSHA-512 (ara mateix és 1234), però podeu canviar-la generant un nou hash amb <code>slappasswd</code>.</li>
<li>Els índexs definits optimitzen les cerques habituals en el directori (per exemple, per uid, cn, sn, mail, etc.).</li>
<li>Els ACLs (Access Control Lists) defineixen qui pot accedir a quins atributs i entrades dins del directori. Per exemple, només l’usuari admin i el root local poden gestionar tot, mentre que els usuaris normals només poden llegir. Ningú més té accés. El root s’aconsegueix amb <code>peercred</code>.</li>
</ul>
</section>
<section id="carregar-la-configuració-de-la-base-de-dades" class="level4">
<h4 class="anchored" data-anchor-id="carregar-la-configuració-de-la-base-de-dades">Carregar la configuració de la base de dades</h4>
<p>Un cop creat el fitxer, carreguem la configuració a la base de dades:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> ldapadd <span class="at">-Y</span> EXTERNAL <span class="at">-H</span> ldapi:/// <span class="at">-f</span> /etc/openldap/rootdn.ldif</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Aquesta comanda:</p>
<ul>
<li><code>ldapadd</code> → eina per afegir entrades a una base de dades LDAP.</li>
<li><code>-Y EXTERNAL</code> → utilitza l’autenticació SASL EXTERNAL, que permet autenticar-se com a usuari del sistema (en aquest cas, root).</li>
<li><code>-H ldapi:///</code> → utilitza el socket local (ldapi) per connectar-se al servidor LDAP.</li>
<li><code>-f rootdn.ldif</code> → fitxer amb la configuració que volem carregar.</li>
</ul>
</section>
</section>
<section id="creació-de-lestructura-del-directori-ldap" class="level3">
<h3 class="anchored" data-anchor-id="creació-de-lestructura-del-directori-ldap">Creació de l’estructura del directori LDAP</h3>
<p>Un cop creada la base de dades MDB i configurat l’usuari administrador (cn=admin,$BASE), ja podem definir l’estructura bàsica del Directori d’Informació (DIT). Aquesta estructura seguirà un patró molt habitual en entorns Linux i empreses:</p>
<ul>
<li><strong>ou=users</strong> → usuaris del sistema</li>
<li><strong>ou=groups</strong> → grups del sistema</li>
<li><strong>ou=system</strong> → comptes o recursos especials</li>
</ul>
<p>Per tant, la nostra estructura bàsica serà:</p>
<ul>
<li><strong>dc=amsa,dc=udl,dc=cat</strong>: Node principal de la jerarquia LDAP.</li>
<li><strong>ou=groups,dc=amsa,dc=udl,dc=cat</strong>. Aquesta entrada representa una organització per als grups. Contindrà entrades de tipus posixGroup o groupOfNames.</li>
<li><strong>ou=users,dc=amsa,dc=udl,dc=cat</strong>. Aquesta entrada representa una organització per als usuaris. Contindrà entrades de tipus inetOrgPerson, posixAccount, o altres objectClasses d’usuaris.</li>
<li><strong>ou=system,dc=amsa,dc=udl,dc=cat</strong>: Aquesta entrada representa una organització per al sistema. És habitual crear aquesta OU per comptes especials del sistema, serveis, ACL internes, o objectes que no són “usuaris reals”.</li>
</ul>
<p>Aquesta estructura fa que el directori sigui ordenat, modular i coherent amb els sistemes Linux quan utilitzen <strong>NSS/LDAP</strong>.</p>
<p>Per a crear aquesta estructura, primer crearem un fitxer LDIF anomenat <code>basedn.ldif</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="va">BASE</span><span class="op">=</span><span class="st">"dc=amsa,dc=udl,dc=cat"</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="va">DC</span><span class="op">=</span><span class="st">"amsa"</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> bash <span class="at">-c</span> <span class="st">"cat &lt;&lt; EOL &gt;&gt; basedn.ldif</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="st">dn: </span><span class="va">$BASE</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: dcObject</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: organization</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: top</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="st">o: AMSA</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="st">dc: </span><span class="va">$DC</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="st">dn: ou=groups,</span><span class="va">$BASE</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: organizationalUnit</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: top</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="st">ou: groups</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="st">dn: ou=users,</span><span class="va">$BASE</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: organizationalUnit</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: top</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="st">ou: users</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a><span class="st">dn: ou=system,</span><span class="va">$BASE</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: organizationalUnit</span></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: top</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a><span class="st">ou: system</span></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a><span class="st">EOL"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Com que el nostre servidor permet <code>peercred</code> com a administrador, podem afegir aquests objectes amb:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> ldapadd <span class="at">-Y</span> EXTERNAL <span class="at">-H</span> ldapi:/// <span class="at">-f</span> basedn.ldif</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled" title="Seguretat del socket ldapi">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Seguretat del socket ldapi
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>-Y EXTERNAL -H ldapi:///</code> és el mètode més segur: autentica via socket Unix com a root local del sistema, sense enviar cap contrasenya. En altres entorns, <code>ldapadd -x -D "cn=admin,$BASE" -W -f basedn.ldif</code> demanarà la contrasenya de l’usuari admin.</p>
</div>
</div>
</section>
<section id="creació-dusuaris-i-grups-dins-del-directori-ldap" class="level3">
<h3 class="anchored" data-anchor-id="creació-dusuaris-i-grups-dins-del-directori-ldap">📂 Creació d’usuaris i grups dins del directori LDAP</h3>
<p>Ara que ja tenim l’estructura bàsica <code>(ou=users, ou=groups, ou=system)</code>, podem començar a crear usuaris i grups reals dins el directori. La creació d’un usuari en LDAP es fa mitjançant un fitxer LDIF que descriu totes les seves propietats.</p>
<section id="exemple-bàsic-creació-dun-usuari" class="level4">
<h4 class="anchored" data-anchor-id="exemple-bàsic-creació-dun-usuari">👤 Exemple bàsic: Creació d’un usuari</h4>
<pre class="ldif"><code>dn: uid=johndoe,ou=users,dc=amsa,dc=udl,dc=cat
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
objectClass: top
cn: John Doe
sn: Doe
uid: johndoe
uidNumber: 1000
gidNumber: 1000
homeDirectory: /home/johndoe
loginShell: /bin/bash
userPassword: {SSHA512}CBVaUdQC9mVvAi+0O92J3hA+aPdiWUqf4lVr6bGRAUsFJX5aFOEb+1pSsY8PQwW1UKuuCGO2+160HotnfjXIaRKlryVekLnu</code></pre>
<p>on:</p>
<ul>
<li><strong>inetOrgPerson</strong>: Permet atributs de persona (nom, cognom, email…).</li>
<li><strong>posixAccount</strong>: Necessari perquè el sistema Linux pugui validar UID, GID, shell, home, etc.</li>
<li><strong>shadowAccount</strong>: Permet gestionar atributs com caducitat de contrasenya.</li>
<li><strong>uidNumber / gidNumber</strong>: Identificadors reals d’usuari i grup.</li>
<li><strong>loginShell</strong>: Shell que s’executarà quan entri al sistema.</li>
<li><strong>userPassword</strong>: Hash generat prèviament (SSHA-512).</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled" title="🔐 Què és un usuari OSProxy?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🔐 Què és un usuari OSProxy?
</div>
</div>
<div class="callout-body-container callout-body">
<p>És habitual crear un usuari especial <strong>OSProxy</strong>, amb la missió de permetre a sistemes Linux consultar:</p>
<ul>
<li>UID d’usuaris</li>
<li>GID de grups</li>
<li>Llistes de membres</li>
</ul>
<p>Això forma part del model de seguretat <strong>least privilege</strong>: Un compte limitat que només pot llegir informació essencial del directori, sense privilegis administratius.</p>
</div>
</div>
</section>
<section id="creació-del-fitxer-users.ldif-amb-usuaris-i-grups" class="level4">
<h4 class="anchored" data-anchor-id="creació-del-fitxer-users.ldif-amb-usuaris-i-grups">🛠️ Creació del fitxer <code>users.ldif</code> amb usuaris i grups</h4>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> bash <span class="at">-c</span> <span class="st">'</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="st">BASE="dc=amsa,dc=udl,dc=cat"</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="st">groups=("programadors" "dissenyadors")</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="st">gids=("4000" "5000")</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="st">users=("ramon" "manel")</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="st">sns=("mateo" "lopez")</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="st">uids=("4001" "5001")</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="st"># Crear fitxer LDIF</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="st">cat &gt; /etc/openldap/users.ldif &lt;&lt; EOL1</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="st">dn: cn=osproxy,ou=system,${BASE}</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: organizationalRole</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: simpleSecurityObject</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="st">cn: osproxy</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="st">userPassword: {SSHA512}CBVaUdQC9mVvAi+0O92J3hA+aPdiWUqf4lVr6bGRAUsFJX5aFOEb+1pSsY8PQwW1UKuuCGO2+160HotnfjXIaRKlryVekLnu</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="st">description: OS proxy for resolving UIDs/GIDs</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="st">EOL1</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="st"># GRUPS</span></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="st">for (( j=0; j&lt;${#groups[@]}; j++ )); do</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a><span class="st">cat &gt;&gt; /etc/openldap/users.ldif &lt;&lt; EOL2</span></span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a><span class="st">dn: cn=${groups[$j]},ou=groups,${BASE}</span></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: posixGroup</span></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a><span class="st">cn: ${groups[$j]}</span></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a><span class="st">gidNumber: ${gids[$j]}</span></span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a><span class="st">EOL2</span></span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a><span class="st">done</span></span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a><span class="st"># USUARIS</span></span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a><span class="st">for (( j=0; j&lt;${#users[@]}; j++ )); do</span></span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a><span class="st">cat &gt;&gt; /etc/openldap/users.ldif &lt;&lt; EOL3</span></span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a><span class="st">dn: uid=${users[$j]},ou=users,${BASE}</span></span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: inetOrgPerson</span></span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: posixAccount</span></span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a><span class="st">objectClass: shadowAccount</span></span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a><span class="st">cn: ${users[$j]}</span></span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a><span class="st">sn: ${sns[$j]}</span></span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a><span class="st">uid: ${users[$j]}</span></span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a><span class="st">uidNumber: ${uids[$j]}</span></span>
<span id="cb28-43"><a href="#cb28-43" aria-hidden="true" tabindex="-1"></a><span class="st">gidNumber: ${uids[$j]}</span></span>
<span id="cb28-44"><a href="#cb28-44" aria-hidden="true" tabindex="-1"></a><span class="st">homeDirectory: /home/${users[$j]}</span></span>
<span id="cb28-45"><a href="#cb28-45" aria-hidden="true" tabindex="-1"></a><span class="st">loginShell: /bin/bash</span></span>
<span id="cb28-46"><a href="#cb28-46" aria-hidden="true" tabindex="-1"></a><span class="st">userPassword: {SSHA512}CBVaUdQC9mVvAi+0O92J3hA+aPdiWUqf4lVr6bGRAUsFJX5aFOEb+1pSsY8PQwW1UKuuCGO2+160HotnfjXIaRKlryVekLnu</span></span>
<span id="cb28-47"><a href="#cb28-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-48"><a href="#cb28-48" aria-hidden="true" tabindex="-1"></a><span class="st">EOL3</span></span>
<span id="cb28-49"><a href="#cb28-49" aria-hidden="true" tabindex="-1"></a><span class="st">done</span></span>
<span id="cb28-50"><a href="#cb28-50" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="carregar-els-usuaris-i-grups-al-directori-ldap" class="level4">
<h4 class="anchored" data-anchor-id="carregar-els-usuaris-i-grups-al-directori-ldap">Carregar els usuaris i grups al directori LDAP</h4>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> ldapadd <span class="at">-Y</span> EXTERNAL <span class="at">-H</span> ldapi:/// <span class="at">-f</span> /etc/openldap/users.ldif</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="testeig-inicial-de-la-installació-ldap-abans-de-tls" class="level3">
<h3 class="anchored" data-anchor-id="testeig-inicial-de-la-installació-ldap-abans-de-tls">🧪 Testeig inicial de la instal·lació LDAP (abans de TLS)</h3>
<section id="buscar-objectes-amb-ldapsearch-mode-local-ldapi" class="level4">
<h4 class="anchored" data-anchor-id="buscar-objectes-amb-ldapsearch-mode-local-ldapi">🔍 Buscar objectes amb ldapsearch (mode local ldapi:///)</h4>
<p>Per comprovar que la base de dades conté els usuaris creats, fem una cerca a <code>ou=users</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="ex">ldapsearch</span> <span class="at">-H</span> ldapi:/// <span class="at">-Y</span> EXTERNAL <span class="at">-b</span> <span class="st">"ou=users,dc=amsa,dc=udl,dc=cat"</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># La sortida ha de mostrar els usuaris creats com el ramon i el manel amb els seus atributs</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="buscar-objectes-amb-ldapsearch-mode-anònim" class="level4">
<h4 class="anchored" data-anchor-id="buscar-objectes-amb-ldapsearch-mode-anònim">🔍 Buscar objectes amb ldapsearch (mode anònim)</h4>
<p>També podem provar una connexió LDAP anònima (sense autenticar) per veure quina informació és accessible públicament:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="ex">ldapsearch</span> <span class="at">-x</span> <span class="at">-H</span> ldapi:/// <span class="at">-b</span> <span class="st">"ou=users,dc=amsa,dc=udl,dc=cat"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Si tot està configurat correctament, hauràs de veure només els atributs que l’ACL permet per a usuaris anònims (normalment molt pocs o cap).</p>
</section>
<section id="prova-amb-lusuari-admin-connexió-autenticada" class="level4">
<h4 class="anchored" data-anchor-id="prova-amb-lusuari-admin-connexió-autenticada">🔐 Prova amb l’usuari admin (connexió autenticada)</h4>
<p>També podem provar una connexió LDAP clàssica utilitzant <code>cn=admin,$BASE</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="ex">ldapsearch</span> <span class="at">-x</span> <span class="at">-W</span> <span class="dt">\</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">-H</span> ldapi:/// <span class="dt">\</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">-D</span> <span class="st">"cn=admin,dc=amsa,dc=udl,dc=cat"</span> <span class="dt">\</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">-b</span> <span class="st">"ou=users,dc=amsa,dc=udl,dc=cat"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>On:</p>
<ul>
<li>El paràmetre -x indica que utilitzem autenticació simple (sense SASL).</li>
<li>El paràmetre -D especifica el DN de l’usuari amb el qual ens autenticarem (admin).</li>
</ul>
</section>
</section>
<section id="altres-comandes-útils-per-a-la-gestió-ldap" class="level3">
<h3 class="anchored" data-anchor-id="altres-comandes-útils-per-a-la-gestió-ldap">Altres comandes útils per a la gestió LDAP</h3>
<p>Aquestes són les eines bàsiques per gestionar qualsevol directori LDAP:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Eina</th>
<th>Funció</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>ldapsearch</strong></td>
<td>Cerca i consulta entrades</td>
</tr>
<tr class="even">
<td><strong>ldapadd</strong></td>
<td>Afegeix entrades (LDIF)</td>
</tr>
<tr class="odd">
<td><strong>ldapmodify</strong></td>
<td>Modifica entrades existents</td>
</tr>
<tr class="even">
<td><strong>ldapdelete</strong></td>
<td>Elimina entrades</td>
</tr>
<tr class="odd">
<td><strong>ldappasswd</strong></td>
<td>Canvia contrasenyes</td>
</tr>
</tbody>
</table>
<p>Us recomano familiaritzar-vos amb aquestes eines, ja que són fonamentals per a l’administració diària d’un servidor LDAP. Feu proves amb elles per entendre com funcionen. Per exemple, podeu provar a canviar la contrasenya d’un usuari amb <code>ldappasswd</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="ex">ldappasswd</span> <span class="at">-H</span> ldapi:/// <span class="dt">\</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">-D</span> <span class="st">"cn=admin,dc=amsa,dc=udl,dc=cat"</span> <span class="dt">\</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">-x</span> <span class="at">-W</span> <span class="dt">\</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"uid=manel,ou=users,dc=amsa,dc=udl,dc=cat"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Aquesta comanda canviarà la contrasenya de l’usuari manel. Et demanarà: la contrasenya de l’admin i després la nova contrasenya per a manel (2 vegades). Recordeu que <code>ldappasswd</code> genera automàticament el hash de la contrasenya. No us cal fer-ho manualment. Podeu introduir la contrasenya en text pla, i <code>ldappasswd</code> s’encarregarà de convertir-la al format correcte (SSHA512).</p>
</section>
<section id="exercicis-dampliació" class="level3">
<h3 class="anchored" data-anchor-id="exercicis-dampliació">Exercicis d’ampliació</h3>
<section id="exercic-1-middleearth.ldif-creació-de-la-base-de-dades-middleearth" class="level4">
<h4 class="anchored" data-anchor-id="exercic-1-middleearth.ldif-creació-de-la-base-de-dades-middleearth">Exercic 1: <code>middleearth.ldif</code> — Creació de la base de dades MiddleEarth</h4>
<p>A partir del que has fet a l’exercici anterior, crea una jerarquia nova per a middleearth dins el teu domini LDAP. Crea un fitxer middleearth.ldif que conté:</p>
<ul>
<li>els grups hobbits, elfs, nans, mags</li>
<li>els seus gidNumber respectius</li>
<li>Afegeix-lo al servidor amb ldapadd.</li>
<li>Comprova que els grups s’han creat amb ldapsearch</li>
</ul>
</section>
<section id="exercici-2-crear-els-usuaris-de-middle-earth" class="level4">
<h4 class="anchored" data-anchor-id="exercici-2-crear-els-usuaris-de-middle-earth">Exercici 2: Crear els usuaris de Middle-Earth</h4>
<p>Crea un fitxer <code>users-middleearth.ldif</code> amb:</p>
<ul>
<li>els usuaris Frodo, Samwise, Gollum, Legolas, Gimli i Gandalf</li>
<li>sn correctes</li>
<li>uidNumber únics</li>
<li>gidNumber que coincideixi amb el seu grup</li>
</ul>
<p>Verifica que pots consultar-los amb <code>ldapsearch</code>.</p>
</section>
<section id="exercici-3-modificar-grup-amb-ldapmodify" class="level4">
<h4 class="anchored" data-anchor-id="exercici-3-modificar-grup-amb-ldapmodify">Exercici 3: Modificar grup amb <code>ldapmodify</code></h4>
<ul>
<li>Modificar el grup actual d’un usuari (per exemple, assigna a Gandalf el grup dels hobbits).</li>
<li>Comprova que el canvi s’ha aplicat correctament amb <code>ldapsearch</code>.</li>
</ul>
</section>
<section id="exercici-4-eliminar-usuari-amb-ldapdelete" class="level4">
<h4 class="anchored" data-anchor-id="exercici-4-eliminar-usuari-amb-ldapdelete">Exercici 4: Eliminar usuari amb <code>ldapdelete</code></h4>
<ul>
<li>Elimina l’usuari Gollum del directori LDAP.</li>
<li>Verifica que ja no existeix amb <code>ldapsearch</code>.</li>
</ul>
</section>
</section>
<section id="configuració-de-certificats-tls-per-ldap-ldaps" class="level3">
<h3 class="anchored" data-anchor-id="configuració-de-certificats-tls-per-ldap-ldaps">🔐 Configuració de certificats TLS per LDAP (LDAPS)</h3>
<p>Per protegir la comunicació amb el servidor LDAP, activarem TLS perquè els clients puguin utilitzar LDAPS (port 636) o LDAP+StartTLS (port 389). Això garanteix que:</p>
<ul>
<li>les contrasenyes viatgen xifrades</li>
<li>totes les consultes i respostes es protegeixen contra interceptació</li>
<li>els clients poden verificar la identitat del servidor</li>
</ul>
<section id="generació-de-certificats-tls-amb-openssl" class="level4">
<h4 class="anchored" data-anchor-id="generació-de-certificats-tls-amb-openssl">Generació de certificats TLS amb OpenSSL</h4>
<p>El primer pas serà generar un parell de claus i un certificat autosignat amb OpenSSL. Això és suficient per a un laboratori, però en producció es faria amb una <strong>CA real</strong>.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="⚠️ IMPORTANT">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>⚠️ IMPORTANT
</div>
</div>
<div class="callout-body-container callout-body">
<p>El Common Name (CN) del certificat ha de coincidir amb el hostname del servidor LDAP que faran servir els clients.</p>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="va">PATH_PKI</span><span class="op">=</span><span class="st">"/etc/pki/tls"</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="va">HOSTNAME</span><span class="op">=</span><span class="st">"ec2-xx-xxx-xxx-xxx.compute-1.amazonaws.com"</span>  <span class="co"># Canvia-ho pel teu hostname públic (DNS Públic)</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="va">commonname</span><span class="op">=</span><span class="va">$HOSTNAME</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="va">country</span><span class="op">=</span>ES</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="va">state</span><span class="op">=</span>Spain</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="va">locality</span><span class="op">=</span>Igualada</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="va">organization</span><span class="op">=</span>UdL</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="va">organizationalunit</span><span class="op">=</span>IT</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="va">email</span><span class="op">=</span>admin@udl.cat</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> openssl req <span class="at">-days</span> 500 <span class="at">-newkey</span> rsa:4096 <span class="dt">\</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">-keyout</span> <span class="st">"</span><span class="va">$PATH_PKI</span><span class="st">/ldapkey.pem"</span> <span class="at">-nodes</span> <span class="dt">\</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">-sha256</span> <span class="at">-x509</span> <span class="at">-out</span> <span class="st">"</span><span class="va">$PATH_PKI</span><span class="st">/ldapcert.pem"</span> <span class="dt">\</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">-subj</span> <span class="st">"/C=</span><span class="va">$country</span><span class="st">/ST=</span><span class="va">$state</span><span class="st">/L=</span><span class="va">$locality</span><span class="st">/O=</span><span class="va">$organization</span><span class="st">/OU=</span><span class="va">$organizationalunit</span><span class="st">/CN=</span><span class="va">$commonname</span><span class="st">/emailAddress=</span><span class="va">$email</span><span class="st">"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Això crearà una clau privada RSA de 4096 bits i un certificat X.509 autosignat vàlid per 500 dies.</p>
</section>
<section id="assignació-de-permisos-1" class="level4">
<h4 class="anchored" data-anchor-id="assignació-de-permisos-1">Assignació de permisos</h4>
<p>La clau privada ha de ser llegible només per l’usuari ldap:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> chown ldap:ldap <span class="st">"</span><span class="va">$PATH_PKI</span><span class="st">/ldapkey.pem"</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> chmod 400 <span class="st">"</span><span class="va">$PATH_PKI</span><span class="st">/ldapkey.pem"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled" title="Què és una CA?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Què és una CA?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una <strong>CA</strong> (Certificate Authority) és una entitat de confiança que emet certificats digitals. Aquests certificats s’utilitzen per verificar la identitat d’un servidor o usuari i per establir connexions segures mitjançant protocols com TLS/SSL. Quan un client es connecta a un servidor, utilitza el certificat emès per la CA per assegurar-se que està comunicant-se amb el servidor legítim i no amb un impostor. <strong>Ens ajuda a establir una cadena de confiança en les comunicacions segures</strong>.</p>
</div>
</div>
<p>Creem també un <strong>CA</strong> (per autosignats utilitzem el mateix certificat):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> cp <span class="st">"</span><span class="va">$PATH_PKI</span><span class="st">/ldapcert.pem"</span> <span class="st">"</span><span class="va">$PATH_PKI</span><span class="st">/cacerts.pem"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>(✔️) Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Verifica que els fitxers s’han creat correctament: <code>openssl x509 -in /etc/pki/tls/ldapcert.pem -noout -text</code></li>
</ul>
</div>
</div>
</section>
</section>
<section id="afegir-la-configuració-tls-al-servidor-ldap" class="level3">
<h3 class="anchored" data-anchor-id="afegir-la-configuració-tls-al-servidor-ldap">Afegir la configuració TLS al servidor LDAP</h3>
<p>Ara crearem un LDIF per dir al servidor LDAP on trobar els certificats.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> bash <span class="at">-c</span> <span class="st">" cat &lt;&lt; EOF &gt; /etc/openldap/add-tls.ldif</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="st">dn: cn=config</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="st">changetype: modify</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="st">add: olcTLSCACertificateFile</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="st">olcTLSCACertificateFile: "</span><span class="va">$PATH_PKI</span>/cacerts.pem<span class="st">"</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="st">-</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="st">add: olcTLSCertificateKeyFile</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="st">olcTLSCertificateKeyFile: "</span><span class="va">$PATH_PKI</span>/ldapkey.pem<span class="st">"</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="st">-</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="st">add: olcTLSCertificateFile</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="st">olcTLSCertificateFile: "</span><span class="va">$PATH_PKI</span>/ldapcert.pem<span class="st">"</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="st">EOF"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled" title="Per què add: i no replace:?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Per què add: i no replace:?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Perquè aquests atributs encara no existeixen en la configuració inicial. Si tornessis a aplicar TLS una segona vegada, aleshores sí que hauries d’usar:</p>
<pre class="ldif"><code>changetype: modify
replace: olcTLSCertificateFile</code></pre>
</div>
</div>
<section id="carregar-la-configuració-tls" class="level4">
<h4 class="anchored" data-anchor-id="carregar-la-configuració-tls">Carregar la configuració TLS</h4>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> ldapadd <span class="at">-Y</span> EXTERNAL <span class="at">-H</span> ldapi:/// <span class="at">-f</span> /etc/openldap/add-tls.ldif</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="reiniciar-el-servei-ldap" class="level4">
<h4 class="anchored" data-anchor-id="reiniciar-el-servei-ldap">Reiniciar el servei LDAP</h4>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> systemctl restart slapd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>(✔️) Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Comprova que el servei s’ha reiniciat correctament: <code>systemctl status slapd</code></li>
<li>Comprova que està escoltant als ports LDAP i LDAPS amb: <code>ss -tuln | grep slapd</code></li>
<li>Pots utilitzar <code>openssl s_client -connect localhost:636 -showcerts</code> per verificar que el certificat TLS s’ha carregat correctament.</li>
<li><code>ldapwhoami -H ldaps://$HOSTNAME -x -D "cn=admin,dc=amsa,dc=udl,dc=cat" -W</code> per assegurar-te que pots autenticar-te via LDAPS.</li>
</ul>
</div>
</div>
</section>
</section>
</section>
<section id="configuració-del-client-ldap" class="level2">
<h2 class="anchored" data-anchor-id="configuració-del-client-ldap">🖥️ Configuració del client LDAP</h2>
<p>En aquest apartat configurarem una nova instància EC2 perquè pugui:</p>
<ul>
<li>validar usuaris LDAP,</li>
<li>utilitzar grups LDAP,</li>
<li>crear automàticament el directori /home/<usuari> quan un usuari LDAP entri al sistema,</usuari></li>
<li>utilitzar LDAPS (TLS) per a totes les connexions.</li>
</ul>
<section id="installar-els-paquets-necessaris" class="level3">
<h3 class="anchored" data-anchor-id="installar-els-paquets-necessaris">Instal·lar els paquets necessaris</h3>
<p>El client necessita eines LDAP i SSSD (System Security Services Daemon), que permet integrar LDAP amb PAM i NSS.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> dnf install <span class="at">-y</span> openldap-clients sssd sssd-tools authselect oddjob-mkhomedir</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><code>openldap-clients</code> → eines com ldapsearch, ldapadd, etc.</li>
<li><code>sssd</code> → daemon que gestiona usuaris i credencials.</li>
<li><code>oddjob-mkhomedir</code> → crea /home/<usuari> automàticament.</usuari></li>
<li><code>authselect</code> → configura PAM/NSS amb SSSD.</li>
</ul>
</section>
<section id="copiar-el-certificat-ca-del-servidor-ldap" class="level3">
<h3 class="anchored" data-anchor-id="copiar-el-certificat-ca-del-servidor-ldap">Copiar el certificat CA del servidor LDAP</h3>
<p>El client ha de confiar en el certificat TLS del servidor.</p>
<p>Al <strong>servidor LDAP</strong>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> cat /etc/pki/tls/cacerts.pem</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Copia TOT el contingut.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Al <strong>client LDAP</strong>:</p>
<p>Crea el fitxer:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> vi /etc/pki/tls/cacert.crt</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Enganxa el contingut.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Es recomana establir permisos restrictius:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> chmod 644 /etc/pki/tls/cacert.crt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="configurar-etcopenldapldap.conf" class="level3">
<h3 class="anchored" data-anchor-id="configurar-etcopenldapldap.conf">Configurar <code>/etc/openldap/ldap.conf</code></h3>
<p>Aquest fitxer indica al client on trobar el servidor LDAP i la CA:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> bash <span class="at">-c</span> <span class="st">"cat &gt; /etc/openldap/ldap.conf &lt;&lt; EOF</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="st">BASE dc=amsa,dc=udl,dc=cat</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="st">URI ldaps://ec2-XX-XXX-XXX-XXX.compute-1.amazonaws.com</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="st">TLS_CACERT /etc/pki/tls/cacert.crt</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="st">EOF"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="configurar-sssd-etcsssdsssd.conf" class="level3">
<h3 class="anchored" data-anchor-id="configurar-sssd-etcsssdsssd.conf">Configurar SSSD <code>/etc/sssd/sssd.conf</code></h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb46"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> bash <span class="at">-c</span> <span class="st">"cat &gt; /etc/sssd/sssd.conf &lt;&lt; EOF</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="st">[sssd]</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="st">services = nss, pam, sudo</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="st">config_file_version = 2</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="st">domains = default</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="st">[nss]</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a><span class="st">[pam]</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a><span class="st">offline_credentials_expiration = 60</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a><span class="st">[domain/default]</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="st">id_provider = ldap</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a><span class="st">auth_provider = ldap</span></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a><span class="st">chpass_provider = ldap</span></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a><span class="st">access_provider = ldap</span></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a><span class="st">sudo_provider = ldap</span></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a><span class="st">cache_credentials = True</span></span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_uri = ldaps://ec2-XX-XXX-XXX-XXX.compute-1.amazonaws.com</span></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_search_base = dc=amsa,dc=udl,dc=cat</span></span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_user_search_base = ou=users,dc=amsa,dc=udl,dc=cat</span></span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_group_search_base = ou=groups,dc=amsa,dc=udl,dc=cat</span></span>
<span id="cb46-24"><a href="#cb46-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-25"><a href="#cb46-25" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_default_bind_dn = cn=osproxy,ou=system,dc=amsa,dc=udl,dc=cat</span></span>
<span id="cb46-26"><a href="#cb46-26" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_default_authtok = 1234</span></span>
<span id="cb46-27"><a href="#cb46-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-28"><a href="#cb46-28" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_tls_reqcert = demand</span></span>
<span id="cb46-29"><a href="#cb46-29" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_tls_cacert = /etc/pki/tls/cacert.crt</span></span>
<span id="cb46-30"><a href="#cb46-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-31"><a href="#cb46-31" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_id_use_start_tls = True</span></span>
<span id="cb46-32"><a href="#cb46-32" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_search_timeout = 50</span></span>
<span id="cb46-33"><a href="#cb46-33" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_network_timeout = 60</span></span>
<span id="cb46-34"><a href="#cb46-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-35"><a href="#cb46-35" aria-hidden="true" tabindex="-1"></a><span class="st">ldap_access_filter = (objectClass=posixAccount)</span></span>
<span id="cb46-36"><a href="#cb46-36" aria-hidden="true" tabindex="-1"></a><span class="st">EOF"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Aquest fitxer configura SSSD per utilitzar LDAP com a font d’usuaris i grups, amb connexió segura via LDAPS. Molt important: assegura’t que <code>ldap_uri</code> i <code>ldap_default_bind_dn</code> coincideixen amb el teu servidor i usuari OSProxy. La contrasenya també ha de ser correcta.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Password en texto plà?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Password en texto plà?
</div>
</div>
<div class="callout-body-container callout-body">
<p>En aquest exemple, la contrasenya de l’usuari osproxy s’ha posat en text pla per simplicitat. En un entorn de producció, és recomanable utilitzar mètodes més segurs per gestionar les contrasenyes, com ara fitxers de contrasenyes xifrats o utilitzar eines de gestió de secrets. Tot i això, recordeu que l’usuari proxy té permisos limitats per llegir només la informació necessària i no pot escriure/modificar res al directori LDAP.</p>
</div>
</div>
<p>Assigneu els permisos correctes:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb47"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> chmod 600 /etc/sssd/sssd.conf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="configurar-authselect" class="level3">
<h3 class="anchored" data-anchor-id="configurar-authselect">Configurar Authselect</h3>
<p><code>authselect</code> és una eina que simplifica la configuració d’autenticació en sistemes Linux. Ens permet no tenir que configurar PAM i NSS manualment.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb48"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> authselect select sssd <span class="at">--force</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="configurar-oddjob-per-a-la-creació-automàtica-de-directoris-dinici" class="level3">
<h3 class="anchored" data-anchor-id="configurar-oddjob-per-a-la-creació-automàtica-de-directoris-dinici">Configurar Oddjob per a la creació automàtica de directoris d’inici</h3>
<p>El servei <code>oddjobd</code> crea els directoris <code>/home/&lt;usuari&gt;</code> quan un usuari LDAP inicia sessió per primera vegada.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb49"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> systemctl enable <span class="at">--now</span> oddjobd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Afegeix la següent línia al fitxer <code>/etc/pam.d/system-auth</code> per habilitar aquesta funcionalitat:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb50"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> bash <span class="at">-c</span> <span class="st">'echo "session optional pam_oddjob_mkhomedir.so skel=/etc/skel/ umask=0077" &gt;&gt; /etc/pam.d/system-auth'</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="iniciar-i-habilitar-sssd" class="level3">
<h3 class="anchored" data-anchor-id="iniciar-i-habilitar-sssd">Iniciar i habilitar SSSD</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb51"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> systemctl enable <span class="at">--now</span> sssd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="testar-la-configuració-del-client-ldap" class="level3">
<h3 class="anchored" data-anchor-id="testar-la-configuració-del-client-ldap">Testar la configuració del client LDAP</h3>
<p>Prova a cercar usuaris LDAP amb <code>id</code> i <code>getent</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb52"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">id</span> ramon</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">getent</span> passwd ramon</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">getent</span> group programadors</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="testar-amb-creació-manual" class="level3">
<h3 class="anchored" data-anchor-id="testar-amb-creació-manual">Testar amb creació manual</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb53"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> mkdir /home/ramon</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> chown 4001::4000 /home/ramon</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="at">-ld</span> /home/ramon</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Si veus que el propietari és ramon i el grup és programadors, tot funciona correctament.</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Si veus, 4001:4000, vol dir que SSSD no està funcionant correctament.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="installació-i-configuració-dun-client-web-ldap-lam" class="level2">
<h2 class="anchored" data-anchor-id="installació-i-configuració-dun-client-web-ldap-lam">🌐 Instal·lació i configuració d’un client web LDAP (LAM)</h2>
<p>Per facilitar l’administració del servidor LDAP, instal·larem LAM — LDAP Account Manager, una interfície web que permet:</p>
<ul>
<li>veure usuaris i grups de manera visual</li>
<li>modificar entrades LDAP</li>
<li>afegir nous usuaris i grups</li>
<li>gestionar contrasenyes</li>
<li>aplicar plantilles d’usuaris i perfils</li>
</ul>
<p>És una eina molt útil perquè els estudiants entenguin com està organitzat el directori i com funcionen els objectClasses. Aquesta configuració es pot fer en la mateixa instància del servidor LDAP o en una instància separada. Nosaltres ho farem en una instància separada per simular un entorn real on el client web està aïllat del servidor LDAP.</p>
<section id="installació-de-dependències" class="level3">
<h3 class="anchored" data-anchor-id="installació-de-dependències">Instal·lació de dependències</h3>
<p>Cal instal·lar Apache i els mòduls PHP necessaris perquè LAM funcioni:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb54"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> dnf install <span class="at">-y</span> httpd php php-ldap php-mbstring php-gd php-gmp php-zip</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> systemctl enable <span class="at">--now</span> httpd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="installació-de-lam" class="level3">
<h3 class="anchored" data-anchor-id="installació-de-lam">Instal·lació de LAM</h3>
<p>Per fer-ho, descarregarem el paquet RPM oficial de LAM i l’instal·larem:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb55"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> wget https://github.com/LDAPAccountManager/lam/releases/download/9.0.RC1/ldap-account-manager-9.0.RC1-0.fedora.1.noarch.rpm</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> dnf install <span class="at">-y</span> ldap-account-manager-9.0.RC1-0.fedora.1.noarch.rpm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled" title="Verifica la versió més recent">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Verifica la versió més recent
</div>
</div>
<div class="callout-body-container callout-body">
<p>Comprova a la pàgina oficial de <a href="https://github.com/LDAPAccountManager/lam/releases">LAM Releases</a> si hi ha una versió més recent i actualitza l’enllaç de descàrrega si cal.</p>
</div>
</div>
<p>LAM quedarà instal·lat a <code>/usr/share/lam</code> i accessible via <strong>http://<server_ip>/lam</server_ip></strong>.</p>
</section>
<section id="configuració-de-lam" class="level3">
<h3 class="anchored" data-anchor-id="configuració-de-lam">Configuració de LAM</h3>
<p>Per configurar LAM, es pot fer des de la interfície web. Accedeix a: <code>http://&lt;IP_SERVER&gt;/lam</code>, el usuari per defecte és <code>lam</code> i la contrasenya també <code>lam</code>. És molt important que canvieu aquesta contrasenya en el primer accés per motius de seguretat.</p>
<p><img src="../../figs/laboratories/05-aws-ldap/lam-01.png" class="img-fluid"></p>
<p>Aneum a <strong>LAM Configuration</strong>:</p>
<ul>
<li>Edit general settings:
<ul>
<li>Importeu el certificat CA del servidor LDAP a la secció <strong>TLS/SSL</strong> per permetre connexions segures. Copieu l’adreça del servidor LDAP (e.g <code>ldaps://XXXXXXXX.compute-1.amazonaws.com:636</code>) i feu clic a <strong>Import from server</strong>.</li>
</ul></li>
<li>Edit server profiles:
<ul>
<li>Server Address: <code>ldaps://XXXXXXXX.compute-1.amazonaws.com:636</code> o bé si esteu utilitzant el vostre servidor LDAP, <code>ldap://localhost:389</code>.</li>
<li>Activate TLS: Marcat.</li>
<li>List of Valid Users: <code>cn=osproxy,ou=system,dc=amsa,dc=udl,dc=cat</code>.</li>
<li>Tree suffix: <code>dc=amsa,dc=udl,dc=cat</code>.</li>
</ul></li>
<li>Account Types:
<ul>
<li>Users: <code>ou=users,dc=amsa,dc=udl,dc=cat</code>.</li>
<li>Groups: <code>ou=groups,dc=amsa,dc=udl,dc=cat</code>.</li>
</ul></li>
<li>List of Valid Users: <code>cn=osproxy,ou=system,dc=amsa,dc=udl,dc=cat</code>.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled" title="Configuració de LAM">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Configuració de LAM
</div>
</div>
<div class="callout-body-container callout-body">
<p>Aquesta configuració es guarda en un fitxer anomenat <code>config.inc.php</code> a <code>/etc/lam/</code>. Si necessites canviar la configuració manualment, pots editar aquest fitxer.</p>
</div>
</div>
</section>
</section>
<section id="testing-de-lam" class="level2">
<h2 class="anchored" data-anchor-id="testing-de-lam">Testing de LAM</h2>
<p>Un cop configurat correctament, hauríeu de poder iniciar sessió a LAM amb l’usuari <code>osproxy</code> i la contrasenya que heu definit anteriorment. Un cop dins, podreu veure i gestionar els usuaris i grups del vostre directori LDAP de manera visual. Ara podeu afegir nous usuaris, modificar els existents i gestionar grups fàcilment.</p>
<p><img src="../../figs/laboratories/05-aws-ldap/lam-04.png" class="img-fluid"></p>
</section>
<section id="project-03-automatització-amb-aws-i-ansible" class="level2">
<h2 class="anchored" data-anchor-id="project-03-automatització-amb-aws-i-ansible">Project 03: Automatització amb AWS i Ansible</h2>
<ul>
<li><a href="../../projects/03-project/03-project.html">Pràctica 03 - Enunciat</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/amsa-gei-udl-2526-105013\.github\.io\/course\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>